name: Custom Build

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    strategy:
      matrix:
        flavor: [ acc ]
        php_version: [ '8.3', '8.1' ]

    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: elcweb/php:${{ matrix.php_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build PHP ${{ matrix.php_version }} - ${{ matrix.flavor }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true 
          context: ./${{ matrix.php_version }}/${{ matrix.flavor }}
          tags: ${{ env.DOCKER_IMAGE }}-${{ matrix.flavor }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}-${{ matrix.flavor }}
          cache-to: type=inline
